name: Scheduled Ping
# This workflow is triggered at a scheduled interval of every 10 minutes
on:
  schedule:
    # * is a special character in YAML so you have to quote this string.
    # every 5 min
    - cron:  '*/5 * * * *'

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
